- name: "Scripts | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files/scripts"
    dest: "$HOME/scripts"
    state: link
  tags:
    - scripts

- name: "Scripts | Create bin"
  ansible.builtin.file:
    path: "$HOME/bin"
    state: directory
  tags:
    - scripts

- name: Copy bin
  copy:
    src: "{{ playbook_dir }}/bin/"
    dest: "$HOME/bin"
    mode: 0755
  tags:
    - scripts

- name: Copy scripts
  copy:
    src: "{{ role_path}}/files/scripts/"
    dest: "$HOME/bin"
    mode: 0755
  tags:
    - scripts
