---
- name: DotFiles Config
  hosts: localhost
  connection: local

  vars_files:
    - "vars/git.yml"
    - "vars/packages.yml"

  vars:
    tmp_dir: "$HOME/.dotfiles-config-tmp"

  pre_tasks:
    - name: Detect WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags:
        - always

  tasks:
    - name: Read installed_roles
      command: "cat $HOME/.dotfiles-info/installed_roles"
      register: installed_roles
      tags:
        - always

    - name: Log
      debug: "msg={{ installed_roles.stdout_lines }}"
      tags:
        - always
      # with_items: "{{ installed_roles.stdout_lines }}"

    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ installed_roles.stdout_lines }}"
      tags:
        - always

    # - name: Set roles
    #   ansible.builtin.set_fact:
    #     run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) | sort }}"
    #   tags:
    #     - always
    #

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
            - "{{ (roles_item | split(':'))[0] }}"
        name: "{{ (roles_item | split(':'))[0] }}"
      vars:
        config_string: "{{ (roles_item | split(':'))[1] | default('') }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always

  post_tasks:
    - name: Remove tmp directory
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: absent
