# $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
---
- name: ZSH | Install via package manager
  package:
    name: zsh
  become: true
  tags:
    - zsh

- name: ZSH | Get executable path
  shell: which zsh
  register: which_zsh
  tags:
    - zsh

- name: ZSH | Change default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ which_zsh.stdout }}"
  tags:
    - zsh

- name: "ZSH | Copy .zshrc"
  ansible.builtin.copy:
    src: "files/.zshrc"
    dest: "$HOME/.zshrc"
    mode: "0644"
