---
- name: "Starship | {{ ansible_distribution }} | Install Starship"
  ansible.builtin.command:
    cmd: which starship
  register: starship_installed
  changed_when: false
  failed_when: false

- name: "Starship | {{ ansible_distribution }} | Install Starship"
  when: starship_installed.rc != 0
  ansible.builtin.shell:
    cmd: curl -fsSL https://starship.rs/install.sh | sudo sh -s -- --force
  args:
    creates: /usr/local/bin/starship

- name: "{{ role_name }} | Ensure .config directory exists"
  ansible.builtin.file:
    path: "$HOME/.config"
    state: directory
    mode: "0755"

- name: "{{ role_name }} | Copy custom starship config"
  ansible.builtin.copy:
    dest: "$HOME/.config/starship.toml"
    src: "files/starship.toml"
    mode: "0644"
